name: Bot Server Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read

env:
  LOCATION: asia-northeast3
  PROJECT_ID: open-run-460313
  SERVICE_NAME: openrun-bot
  DOCKER_CONTAINER_PATH: asia-northeast3-docker.pkg.dev/open-run-460313
  DOCKER_REPOSITORY_NAME: openrun-bot
  DOCKER_IMAGE_NAME: openrun-bot

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCP_DEPLOYMENT_SA_KEY }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: "${{ env.PROJECT_ID }}"

      - name: Configure Docker to use gcloud as a credential helper
        run: gcloud auth configure-docker ${{ env.LOCATION }}-docker.pkg.dev

      - name: Create Artifact Registry Repository if it doesn't exist
        run: |
          if ! gcloud artifacts repositories describe ${{ env.DOCKER_REPOSITORY_NAME }} --location=${{ env.LOCATION }} 2>/dev/null; then
            gcloud artifacts repositories create ${{ env.DOCKER_REPOSITORY_NAME }} \
              --repository-format=docker \
              --location=${{ env.LOCATION }} \
              --description="Docker repository for OpenRun Bot"
          fi

      - name: Build the Docker image
        run: |
          docker build . \
            --tag ${{ env.DOCKER_CONTAINER_PATH }}/${{ env.DOCKER_REPOSITORY_NAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest \
            --tag ${{ env.DOCKER_CONTAINER_PATH }}/${{ env.DOCKER_REPOSITORY_NAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}

      - name: Push the Docker image
        run: |
          docker push ${{ env.DOCKER_CONTAINER_PATH }}/${{ env.DOCKER_REPOSITORY_NAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest
          docker push ${{ env.DOCKER_CONTAINER_PATH }}/${{ env.DOCKER_REPOSITORY_NAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image=${{ env.DOCKER_CONTAINER_PATH }}/${{ env.DOCKER_REPOSITORY_NAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }} \
            --region=${{ env.LOCATION }} \
            --platform=managed \
            --port=8000 \
            --memory=1Gi \
            --cpu=1 \
            --min-instances=0 \
            --max-instances=3 \
            --allow-unauthenticated \
            --set-env-vars="OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}"
